language: "node_js"

node_js:
  - "8"
  - "node"

script:
  - npm run lint
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json

notifications:
  email:
    false